# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d36209be6c2ab5b19846e041570bb918fb28f6abc3816dbc8dc9c9ce7b1e977d8f89a53224ba5ff58f38153253c5c8f25b89ed314e5514e382e52ef3bc3d27a6

test:
  secret_key_base: a247e804879ef2af1e2fd34fca9ad7fa97a10977cd4e67bd03a9c01569ddf978ab00379b257e52387569aaa5f70ec68170b3ab4db5ff8ec8258ff7ac1deb5e3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
